/**
 * 预设图标注册表
 *
 * 定义 Treasure 平台支持的 Element Plus 内置图标白名单。
 * 插件开发者可直接使用这些预设名，无需提供自定义图标文件。
 *
 * 使用方式：
 *   import { PRESET_ICONS, isPresetIcon } from '@/constants/presetIcons';
 */

/** Element Plus 内置图标白名单（按用途分组） */
export const PRESET_ICONS = [
  // ── 基础操作 ──────────────────────────────────────────────
  'HomeFilled',
  'Setting',
  'Document',
  'FolderOpened',
  'Folder',
  'Files',
  'DocumentFilled',
  'Menu',
  'Grid',
  'List',
  'Rank',
  'Suitcase',
  'Briefcase',
  'Goods',
  'Box',

  // ── 编辑 ──────────────────────────────────────────────────
  'EditPen',
  'Delete',
  'Check',
  'Close',
  'Refresh',
  'RefreshLeft',
  'RefreshRight',
  'Search',
  'Select',
  'CircleCheck',
  'CircleCheckFilled',
  'CircleClose',
  'CircleCloseFilled',
  'SuccessFilled',
  'ErrorFilled',
  'WarningFilled',
  'InfoFilled',
  'QuestionFilled',

  // ── 导航 ──────────────────────────────────────────────────
  'ArrowLeft',
  'ArrowRight',
  'ArrowDown',
  'ArrowUp',
  'ArrowUpBold',
  'ArrowDownBold',
  'DArrowLeft',
  'DArrowRight',
  'CaretLeft',
  'CaretRight',
  'CaretBottom',
  'CaretTop',
  'Expand',
  'Fold',
  'Back',
  'Top',
  'Bottom',
  'Sort',
  'SortUp',
  'SortDown',

  // ── 数据 / 分析 ───────────────────────────────────────────
  'DataAnalysis',
  'TrendCharts',
  'PieChart',
  'Histogram',
  'DataLine',
  'DataBoard',
  'Chart',
  'Opportunity',
  'Cpu',
  'Monitor',
  'Mobike',
  'Shop',
  'ShoppingBag',
  'ShoppingCart',
  'ShoppingCartFull',
  'Tickets',
  'Money',
  'Coin',
  'Wallet',
  'BankCard',
  'Discount',

  // ── 媒体 ──────────────────────────────────────────────────
  'Picture',
  'PictureFilled',
  'PictureRounded',
  'VideoPlay',
  'VideoPause',
  'Headset',
  'Microphone',
  'Camera',
  'CameraFilled',
  'VideoCamera',
  'VideoCameraFilled',

  // ── 通讯 ──────────────────────────────────────────────────
  'ChatLineSquare',
  'ChatDotSquare',
  'ChatSquare',
  'Message',
  'Mail',
  'Phone',
  'Cellphone',
  'Connection',
  'Link',
  'Share',
  'Upload',
  'Download',
  'Position',
  'Location',
  'LocationFilled',
  'MapLocation',

  // ── 安全 ──────────────────────────────────────────────────
  'Lock',
  'Unlock',
  'Key',
  'Shield',
  'ShieldCheck',
  'Aim',
  'Eye',
  'EyeFilled',
  'Hide',
  'View',

  // ── 工具 ──────────────────────────────────────────────────
  'Filter',
  'Star',
  'StarFilled',
  'Timer',
  'AlarmClock',
  'Clock',
  'Calendar',
  'CalendarFilled',
  'Date',
  'TakeawayBox',
  'RemoveFilled',
  'CirclePlusFilled',
  'Plus',
  'Minus',
  'CirclePlus',
  'CircleMinus',
  'Pointer',
  'Laptop',
  'Keyboard',
  'Printer',
  'Scissor',
  'MagicStick',
  'Brush',
  'Basketball',
  'Football',
  'Baseball',
  'Trophy',
  'Medal',
  'Flag',
  'Guide',
  'Help',
  'Bell',
  'BellFilled',
  'MessageFilled',
  'ChatDotRound',
  'ChatLineRound',
  'PhoneFilled',
  'Mouse',
  'SemiSelect',
  'DocumentAdd',
  'DocumentDelete',
  'DocumentChecked',
  'Reading',
  'ReadingLamp',
  'Notebook',
  'Stamp',
  'Management',
  'Postcard',
  'Messages',
  'ChatRound',
  'ChatRoundFilled',
  'Paperclip',
  'Pushpin',
  'PushpinFilled',
  'Place',
  'FirstAidKit',
  'FirstAidKitFilled',
  'Van',
  'Car',
  'Bicycle',
  'Ship',
  'Train',
  'Plane',
  'Present',
  'PresentFilled',
  'IceCream',
  'IceCreamFilled',
  'IceTea',
  'IceTeaFilled',
  'Food',
  'FoodFilled',
  'Dish',
  'DishDot',
  'KnifeFork',
  'Chicken',
  'Apple',
  'Cherry',
  'Watermelon',
  'Grape',
  'Orange',
  'Lollipop',
  'IceCreamSquare',
  'IceCreamRound',
  'ColdDrink',
  'MilkTea',
  'Sugar',
  'Hamburger',
  'Tableware',
  'Bowl',
  'Goblet',
  'GobletFull',
  'Goat',
  'Deer',
  'Horse',
  'Dog',
  'Cat',
  'SGlasses',
  'Glasses',
  'Sunglasses',
] as const;

/** 预设图标类型 */
export type PresetIcon = typeof PRESET_ICONS[number];

/** 预设图标集合（用于快速查找） */
export const PRESET_ICON_SET: Set<string> = new Set(PRESET_ICONS);

/**
 * 检查名称是否为有效预设图标
 * @param name 图标名称
 * @returns 是否为预设图标
 */
export function isPresetIcon(name: string): boolean {
  return PRESET_ICON_SET.has(name);
}
